### ISSUE TITLE
Impossible to update user avatar

### ISSUE THREAD

**Issue by leoduquesnel** [discourse/discourse_api#100]
Hi, 

I'm trying to update my avatar, but I've got a really strange error : 
```
client = DiscourseApi::Client.new("https://my-discourse-forum.com")
client.api_key = "f5313083007c5650c37378417e1fca95"
client.api_username = "my_username"

client.update_avatar(username: "other_username",
                     url: "url_to_image.JPG")
```
And I've got:
```
DiscourseApi::Error:
from /Users/leo/.rvm/gems/ruby-2.2.3/gems/discourse_api-0.7.0/lib/discourse_api/client.rb:77:in `post'
```

**Comment by oblakeerickson** [comment]
Is the image publicly accessible?

![screenshot_011916_021623_pm](https://cloud.githubusercontent.com/assets/1490496/12432208/3efd078c-beb7-11e5-9aa4-89a7207f468a.jpg)

**Comment by leoduquesnel** [comment]
Yes it is, it's a fake url in my example

**Comment by oblakeerickson** [comment]
Hmm... I'm able to get it to work just fine. 

![screenshot from 2016-01-19 20 35 14](https://cloud.githubusercontent.com/assets/1490496/12439326/84e0a008-beec-11e5-893d-3c9b9d59394f.png)

Can you try another image?

**Comment by leoduquesnel** [comment]
I tried and now I've got:  

`TypeError: exception class/object expected
from /Users/leo/.rvm/gems/ruby-2.2.3/gems/discourse_api-0.7.0/lib/discourse_api/client.rb:77:in `post'`

**Comment by oblakeerickson** [comment]
Are you able to upload an avatar in your Discourse using the web interface?

**Comment by leoduquesnel** [comment]
My mistake, I have enabled an option in admin to not allow users to upload their pictures. But I did not know that this affects API too.

**Comment by oblakeerickson** [comment]
Glad you got it working!
