### ISSUE TITLE
What exactly does "client.sync_sso" do?

### ISSUE THREAD

**Issue by cbeck88** [discourse/discourse_api#104]
Does it perform some sort of db query?
Does it only search among currently logged in users?
When I pass a table to "sync", can that change the logged-in status or DB status? Or is it only "fill in this query with data from the matching entry in the db?"

Some more documentation would be helpful, thank you!

**Comment by oblakeerickson** [comment]
@cbeck88 thank you for opening an issue. I can't really answer your question off the top of my head right now. Can you create a topic on discourse meta? it will probably get a lot more eyeballs. Thanks!

**Comment by oblakeerickson** [comment]
see https://meta.discourse.org/t/what-exactly-does-client-sync-sso-do-discourse-ruby-api
