### ISSUE TITLE
Get all users from a group?

### ISSUE THREAD

**Issue by alaouy** [discourse/discourse_api#105]
Is there any feature to get all users belonging to a certain group?

**Comment by oblakeerickson** [comment]
There doesn't appear to be. How far does `list_users(type)` get you? Once you get all the users can you then filter by group?

**Comment by oblakeerickson** [comment]
@alaouy you can now use the `group_members` method to get what you are looking for :)

**Comment by alaouy** [comment]
@oblakeerickson Thanks 👍
