### ISSUE TITLE
Is there a login API?

### ISSUE THREAD

**Issue by AsoulYang** [discourse/discourse_api#120]
Hi,
I'm new to discourse API, is there any document?

I want to connect discourse login system with my own database,
and searching for something like login, logout, signup API

Thanks

**Comment by oblakeerickson** [comment]
I'm not really sure what you are asking? but this project is for connection to a Discourse instance with ruby. You can get an api key and then query for users. Each user probably has a last logged in attribute.


This guide might help:
https://meta.discourse.org/t/discourse-api-documentation/22706

**Comment by AsoulYang** [comment]
Thanks @oblakeerickson,
the repository name confuses me 😄
