### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by alaouy** [discourse/discourse_api#131]
I changed the ssl certificat of main dormaine name, and when trying to login to discourse as a user I get this error :
```
DiscourseApi::Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

**Comment by oblakeerickson** [comment]
I would also post this issue on meta.discourse.org because a lot more eye balls will see it. I'm not really sure how to solve the problem you are having at the moment.

**Comment by alaouy** [comment]
@oblakeerickson Thanks, I updated my ssl config on a new droplet with the latest discourse version.
