### ISSUE TITLE
Anyway update the number of likes in topics/posts?

### ISSUE THREAD

**Issue by hunkim** [discourse/discourse_api#132]
I really like this implementation. Thanks a lot!

Is there anyway to update the number of likes using doscourse_api? It seems we don't have any implementation to update it.

**Comment by oblakeerickson** [comment]
Is this what you are after?

https://github.com/discourse/discourse_api/blob/master/examples/post_action.rb

You can't just update the number of likes but as a user you can like a post through the api using a post_action

**Comment by hunkim** [comment]
Super. @oblakeerickson I want to make it an arbitrary number (n) like 10 or 101. Should I perform the action with n user ids? Or one user id can increase the like numbers to 10 or 100? Thanks!

**Comment by oblakeerickson** [comment]
I don't think there is a way to set an arbitrary number.

**Comment by hunkim** [comment]
@oblakeerickson Thanks!
