### ISSUE TITLE
Does hot topics still exist?

### ISSUE THREAD

**Issue by djsegal** [discourse/discourse_api#134]
The `readme` makes it sound like a thing, but the code doesn't exist anywhere.

Was it taken out at some point? If so, why?

**Comment by oblakeerickson** [comment]
It doesn't appear to exist anymore.

It was removed from discourse_api in this commit:

https://github.com/discourse/discourse_api/commit/1c1fcbf0a34c527a7a3e98b28fd1810cc5a6fcdb#diff-4381f18a70346b58f5aca33bda393ddf

Not sure when /hot was removed from discourse/discourse (over 2 years ago)

I'm not sure why it was removed.
