### ISSUE TITLE
Getting user details based on email

### ISSUE THREAD

**Issue by p29892p** [discourse/discourse_api#136]
Hi there,

How can i check whether user existed or not based on his/her email id. Please some one tell me if one exists. It's very important to us now. Any suggestions appreciated. Thanks

**Comment by oblakeerickson** [comment]
I suppose you could send a post request to the /users endpoint and try and create the user with that email. It should error if the email already exists.

**Comment by p29892p** [comment]
@oblakeerickson, Yes that is one way to check whether user existed or not with particular email, but what response will be returned if a user exist and how to get details including user_id, name, etc using email address? Thanks for response.

**Comment by oblakeerickson** [comment]
The POST request is definitely not the best way to do it. It is was Discourse uses in the sign up page though to make sure we don't have duplicate Users.

I don't think we have a public api call to search by email address. You might have to export users and scan the csv file or something to accomplish what you want. You can only use the API to search for users by username.

**Comment by p29892p** [comment]
I'm getting users list by applying filters to this api call 
**response = connection.get '/admin/users/list/active.json?filter='+user.email** 
but it is not sending email address of the users. I even tried to get email address by calling below api call
**get("/users/#{username}.json", params)** and this is also not sending email address. May i know is there any way to get user email address from discourse through api call.

**Comment by oblakeerickson** [comment]
You need to include `show_emails=true`

http://localhost:3000/admin/users/list/active.json?filter=&show_emails=true&_=1486603491399

**Comment by p29892p** [comment]
@oblakeerickson That's working fine. Now i can get emails along with user details.  

Any way when i perform filter operation with email, I'm getting at most one record or zero if any user with particular email not found. So that i can pick first user as a user with given email.  

if response.body.size > 0
      $discourse_user = response.body[0]
      Rails.application.config.discourse_client.api_username = response.body[0]['username']
end

As per your suggestion i tried to call api end point as below:
**response = connection.get '/admin/users/list/active.json?filter='+user.email+'&show_emails=true'**

with this i can get emails as well.

Thanks a lot for your support.

**Comment by p29892p** [comment]
@oblakeerickson What is the main purpose of sync_sso? Does it have any effect on user actions through api when sso enabled in discourse.
