### ISSUE TITLE
How to post comments by particular user?

### ISSUE THREAD

**Issue by p29892p** [discourse/discourse_api#137]
I embedded discourse comments in my website. Now i want to post user comments through api. I wrote below snippet to perform post operation.

`post_comment = $client.create_post(
      :topic_id => params[:discourse_topic_id],
      :raw => params[:post_content]
    )`

The above code posting comments successfully, but i'm getting other users as posted by instead of logged in user. How can i post comments by logged in user? Please help me to resolve this.

Thanks

**Comment by oblakeerickson** [comment]
As an admin you should be able to change the user of the post.

Not really sure how this would work, but could generate a user specific api token for each of your logged in users and pass that to your api code so that each user is using their own api token and posting as themselves.

**Comment by p29892p** [comment]
Ok. It is better to have an example. Please tell me one thing, is there any necessity to perform **sync_sso**  for api_users. Does it shows any effect on user operations such as topic creation, posting comments, etc.

**Comment by oblakeerickson** [comment]
I think the sync_sso is just to make sure a user on your system gets added/updated discourse. I'm not sure if that would help you or not, but a user would have to exist in Discourse if you wanted to post as them.

**Comment by p29892p** [comment]
Yes, that for sure. We can post comments by user only when he/she existed in discourse. 
Here i'll tell you what are the sequence of steps i'm performing

1. When a user logged into my rails application i'm checking whether he existed in discourse or not by using admin user as api_username.
**Discourse_client.api_username = 'adminuser'**

2. Fetching user created topics by using following api call.
**@discourse_user_topics = $client.topics_by($discourse_user['username'])**

3. Had a screen to show user comments by using embedding discourse comments functionality.
4. Gave a textarea field to user to post comments for particular topic.
5. Now when a user posted comment by using textare which was provided, i'm changing api_username as current_user username in discourse and performing api call.

**$client.api_username = current_username_discourse**

When this action performed comments are posting as admin user. May i know by default which user is taken to post a comment?

**Comment by oblakeerickson** [comment]
I think if you want to use the admin api token you need to POST the comment and then do a PUT request to change the user . 

If you want to POST as a particular user you will need to use their API key.

https://meta.discourse.org/t/discourse-api-documentation/22706/192?u=oblakeerickson

https://meta.discourse.org/t/user-api-keys-specification/48536

**Comment by p29892p** [comment]
Do you mean that api_key is different for every user?

**Comment by coding-horror** [comment]
This is for code bugs not general "how do I do this?" support.
