### ISSUE TITLE
NoMethodError: undefined method `category_latest_posts'

### ISSUE THREAD

**Issue by birchlore** [discourse/discourse_api#138]
I've connected successfully to client and able to call such methods as `client.new_topics` with no issue. But when I call `client.category_latest_posts("my-category-slug")`  I get below error:

> NoMethodError: undefined method `category_latest_posts'

How do I get a list of posts in a category? What about latest topics in a category? And posts in a topic?

**Comment by oblakeerickson** [comment]
You need to use something like

`client.category_latest_topics(category_slug: "lounge")`

instead

**Comment by birchlore** [comment]
Hey thanks a lot for looking into this. I'm going to open a new thread about getting latest topics in a category and latest posts in a topic.
