### ISSUE TITLE
Inconsistent error handling for different kind of requests

### ISSUE THREAD

**Issue by mrhead** [discourse/discourse_api#142]
When a POST request returns some other status code than 200 then `DiscourseApi::Error` is raised. But this doesn't apply to other request types. For example a GET request returning a 500 status code doesn't raise any error.

Is there any particular reason why POST requests are handled differently? Do we want to fix this behaviour?

**Comment by oblakeerickson** [comment]
There is not a reason that I'm aware of why POST requests are handled differently. If you would like to fix this that would be great.

**Comment by vietqhoang** [comment]
PR #143 may have addressed the issue.

**Comment by mrhead** [comment]
Thanks @vietqhoang!
