### ISSUE TITLE
sync_sso Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by wilk916** [discourse/discourse_api#57]
I am attempting to use the sync_sso API to adjust user information in my instance of discourse.  However, I receive a 500 response to the URL post.  The error logs show:

Can't verify CSRF token authenticity
Discourse::InvalidParameters (url)

I have verified that the SSO secret and URL are correct.

**Comment by oblakeerickson** [comment]
Closing this issue. It appears it is still open on discourse meta though: https://meta.discourse.org/t/discourse-api-error-using-sync-sso/23063/3
