### ISSUE TITLE
Can't load dotenv

### ISSUE THREAD

**Issue by fate-lovely** [discourse/discourse_api#80]
**cannot load such file -- dotenv (LoadError)**
```
CJ-MBP:sike/ git:(master) ✗gem list | grep dotenv
dotenv (2.0.1, 1.0.2)
```

I use figaro rather than dotenv in my project. 
But even though I installed dotenv, I still can't start rails.
Maybe dependent on dotenv is not a good idea?
We should init client explicitly?

**Comment by oblakeerickson** [comment]
The [latest version (0.4.2)](https://rubygems.org/gems/discourse_api) has dotenv as a [development dependency](https://github.com/discourse/discourse_api/commit/859655aafb1e65495394089c577df16a4311ae65). 
By definition this shouldn't be used anymore. Can you try removing the dotenv gem and make sure you are using discourse_api 0.4.2?

**Comment by woto** [comment]
Hi, same issue after update.

```
➜  yaponama_2012 git:(master) ✗ ./bin/rails g migration Aaa
/home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- dotenv (LoadError)
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/discourse_api-43e5f11439ca/lib/discourse_api/client.rb:1:in `<top (required)>'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/discourse_api-43e5f11439ca/lib/discourse_api.rb:2:in `<top (required)>'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/bundler-1.7.4/lib/bundler/runtime.rb:76:in `require'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/bundler-1.7.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/bundler-1.7.4/lib/bundler/runtime.rb:72:in `each'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/bundler-1.7.4/lib/bundler/runtime.rb:72:in `block in require'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/bundler-1.7.4/lib/bundler/runtime.rb:61:in `each'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/bundler-1.7.4/lib/bundler/runtime.rb:61:in `require'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/bundler-1.7.4/lib/bundler.rb:133:in `require'
        from /home/woto/rails/yaponama_2012/config/application.rb:8:in `<top (required)>'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application.rb:82:in `require'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application.rb:82:in `preload'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/woto/.rbenv/versions/2.1.4/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

**Comment by woto** [comment]
Found, here is it.

https://github.com/discourse/discourse_api/blob/master/lib/discourse_api/client.rb#L1

**Comment by woto** [comment]
@oblakeerickson hi, not sure that you recived notification.

**Comment by oblakeerickson** [comment]
dotenv is a [development dependency](http://guides.rubygems.org/patterns/) [inside of discourse_api](https://github.com/discourse/discourse_api/commit/859655aafb1e65495394089c577df16a4311ae65) so now that you are on the new version you just need to remove all existing dotenv gems on your system:

    gem uninstall dotenv

It will ask you which versions you want to remove, I would remove them all.

You then might need to run bundle install again on your rails app so that it can install the right version of dotenv.

You should be good to go after that.

On a clean linux box, I just installed ruby and discourse_api and dotenv isn't even installed:

    root@dave:~# gem install discourse_api
    Fetching: rack-1.6.1.gem (100%)
    Successfully installed rack-1.6.1
    Fetching: multipart-post-2.0.0.gem (100%)
    Successfully installed multipart-post-2.0.0
    Fetching: faraday-0.9.1.gem (100%)
    Successfully installed faraday-0.9.1
    Fetching: faraday_middleware-0.9.1.gem (100%)
    Successfully installed faraday_middleware-0.9.1
    Fetching: discourse_api-0.4.2.gem (100%)
    Successfully installed discourse_api-0.4.2
    Parsing documentation for rack-1.6.1
    Installing ri documentation for rack-1.6.1
    invalid options: -SHN
    (invalid options are ignored)
    Parsing documentation for multipart-post-2.0.0
    Installing ri documentation for multipart-post-2.0.0
    Parsing documentation for faraday-0.9.1
    Installing ri documentation for faraday-0.9.1
    Parsing documentation for faraday_middleware-0.9.1
    Installing ri documentation for faraday_middleware-0.9.1
    Parsing documentation for discourse_api-0.4.2
    Installing ri documentation for discourse_api-0.4.2
    Done installing documentation for rack, multipart-post, faraday, faraday_middleware,     discourse_api after 5 seconds
    5 gems installed
    
    root@dave:~# gem list
    
    *** LOCAL GEMS ***
    
    bigdecimal (1.2.6)
    bundler (1.8.4)
    bundler-unload (1.0.2)
    discourse_api (0.4.2)
    executable-hooks (1.3.2)
    faraday (0.9.1)
    faraday_middleware (0.9.1)
    gem-wrappers (1.2.7)
    io-console (0.4.3)
    json (1.8.1)
    minitest (5.4.3)
    multipart-post (2.0.0)
    power_assert (0.2.2)
    psych (2.0.8)
    rack (1.6.1)
    rake (10.4.2)
    rdoc (4.2.0)
    rubygems-bundler (1.4.4)
    rvm (1.11.3.9)
    test-unit (3.0.8)
