### ISSUE TITLE
Feature Request: APIs around Groups

### ISSUE THREAD

**Issue by metalivedev** [discourse/discourse_api#87]
I'd like to use the API to create/delete groups and to change their membership.

**Comment by SamSaffron** [comment]
The API endpoints are there, @techAPJ can you add an example?

**Comment by techAPJ** [comment]
API examples for creating/managing groups are already present: https://github.com/discourse/discourse_api/blob/master/examples/groups.rb

I just added an API example for deleting group: https://github.com/discourse/discourse_api/commit/50cff1f7d7c007d110789176ea7f08ef89ac79e3
