### ISSUE TITLE
Feature Request: Set Permissions to have Private Categories

### ISSUE THREAD

**Issue by melissawahnish** [discourse/discourse_api#90]
I would like to add an endpoint to add permissions on a category to make that category private.

I propose a method called set_category_permissions that would accept the group id and the permission level.  It would use a simple PUT call to the Discourse app to edit the category.

**Comment by jmay** [comment]
It looks as if `category#update` has not been implemented in this API wrapper, either for permissions or anything else. That would be useful.

Note that to restrict access to a category you need to remove the Everyone permission, not just add the new group.

**Comment by melissawahnish** [comment]
Yes, I think making a category#update would be good too. After playing around a bit, I discovered you have to submit all of the required attributes again anyway.

For now, I am just going to add it to creating a category and put in a spec for that!  I will try to work on update soon.

I think I can just submit permissions and Discourse will then restrict the access.  The methods around permissions in app/models/categories.rb set read_restricted to true.

**Comment by melissawahnish** [comment]
Created pull request #91 

Closing this issue.  Thanks jmay!
